using System.Text.Json;
using System.Text.Json.Serialization;
using Hume;
using Hume.Core;

namespace Hume.ExpressionMeasurement.Batch;

[Serializable]
public record CompletedInference : IJsonOnDeserialized
{
    [JsonExtensionData]
    private readonly IDictionary<string, JsonElement> _extensionData =
        new Dictionary<string, JsonElement>();

    /// <summary>
    /// When this job was created (Unix timestamp in milliseconds).
    /// </summary>
    [JsonPropertyName("created_timestamp_ms")]
    public required long CreatedTimestampMs { get; set; }

    /// <summary>
    /// When this job started (Unix timestamp in milliseconds).
    /// </summary>
    [JsonPropertyName("started_timestamp_ms")]
    public required long StartedTimestampMs { get; set; }

    /// <summary>
    /// When this job ended (Unix timestamp in milliseconds).
    /// </summary>
    [JsonPropertyName("ended_timestamp_ms")]
    public required long EndedTimestampMs { get; set; }

    /// <summary>
    /// The number of predictions that were generated by this job.
    /// </summary>
    [JsonPropertyName("num_predictions")]
    public required ulong NumPredictions { get; set; }

    /// <summary>
    /// The number of errors that occurred while running this job.
    /// </summary>
    [JsonPropertyName("num_errors")]
    public required ulong NumErrors { get; set; }

    [JsonIgnore]
    public ReadOnlyAdditionalProperties AdditionalProperties { get; private set; } = new();

    void IJsonOnDeserialized.OnDeserialized() =>
        AdditionalProperties.CopyFromExtensionData(_extensionData);

    /// <inheritdoc />
    public override string ToString()
    {
        return JsonUtils.Serialize(this);
    }
}
