using System.Text.Json;
using System.Text.Json.Serialization;
using Hume;
using Hume.Core;

namespace Hume.EmpathicVoice;

/// <summary>
/// A description of a single event in a chat returned from the server
/// </summary>
[Serializable]
public record ReturnChatEvent : IJsonOnDeserialized
{
    [JsonExtensionData]
    private readonly IDictionary<string, JsonElement> _extensionData =
        new Dictionary<string, JsonElement>();

    /// <summary>
    /// Identifier for the chat this event occurred in. Formatted as a UUID.
    /// </summary>
    [JsonPropertyName("chat_id")]
    public required string ChatId { get; set; }

    /// <summary>
    /// Stringified JSON with data about emotional content/prosody of the event.
    /// </summary>
    [JsonPropertyName("emotion_features")]
    public string? EmotionFeatures { get; set; }

    /// <summary>
    /// Identifier for a chat event. Formatted as a UUID.
    /// </summary>
    [JsonPropertyName("id")]
    public required string Id { get; set; }

    /// <summary>
    /// The text of the chat message, either transcribed from speaker audio or generated by the agent.
    /// </summary>
    [JsonPropertyName("message_text")]
    public string? MessageText { get; set; }

    /// <summary>
    /// Stringified JSON with additional metadata about the chat event.
    /// </summary>
    [JsonPropertyName("metadata")]
    public string? Metadata { get; set; }

    /// <summary>
    /// Identifier for a related chat event. Currently only seen on ASSISTANT_PROSODY events, to point back to the ASSISTANT_MESSAGE that generated these prosody scores
    /// </summary>
    [JsonPropertyName("related_event_id")]
    public string? RelatedEventId { get; set; }

    [JsonPropertyName("role")]
    public required ReturnChatEventRole Role { get; set; }

    /// <summary>
    /// The timestamp when the chat event occurred, formatted as a Unix epoch milliseconds.
    /// </summary>
    [JsonPropertyName("timestamp")]
    public required long Timestamp { get; set; }

    [JsonPropertyName("type")]
    public required ReturnChatEventType Type { get; set; }

    [JsonIgnore]
    public ReadOnlyAdditionalProperties AdditionalProperties { get; private set; } = new();

    void IJsonOnDeserialized.OnDeserialized() =>
        AdditionalProperties.CopyFromExtensionData(_extensionData);

    /// <inheritdoc />
    public override string ToString()
    {
        return JsonUtils.Serialize(this);
    }
}
